### ISSUE TITLE
New Favicon ⛺

### ISSUE THREAD

**Issue by ManuelVargas1251** [ManuelVargas1251/Chord-Finder#37]
@lucas-garcon Can you please make a new favicon for this web app?

Below is what I currently have

![image](https://user-images.githubusercontent.com/10030407/44128022-0d4f9f3c-a006-11e8-90dc-b968ffe8bcb8.png)

**Comment by lag0215** [comment]
![image](https://user-images.githubusercontent.com/21995580/44163519-4eee3d80-a089-11e8-90f0-b9659003e121.png)

new logo, just something super simple where the c and f come together to make a note-like shape. added hash in there to solidify and also bc it's both a sharp symbol but also a modern day identifier (hashtags).... and i like vermilion, don't fight me on this please.

**Comment by ManuelVargas1251** [comment]
This issue is specifically about updating the favicon. If you would like, please create a new issue about updating the logo.

**Comment by ManuelVargas1251** [comment]
I'm closing this and adding it to the requirements for the logo issue https://github.com/ManuelVargas1251/Chord-Finder/issues/39
