### ISSUE TITLE
New Logo Proposition

### ISSUE THREAD

**Issue by ghost** [ManuelVargas1251/Chord-Finder#38]
![image](https://user-images.githubusercontent.com/21995580/44164599-1a2fb580-a08c-11e8-8498-3dde5d89d9f1.png)

Proposing new logo, see above.

**Comment by ManuelVargas1251** [comment]
super unrelated but you are in two accounts. Please try to delete the account you don't use anymore
![image](https://user-images.githubusercontent.com/10030407/44165263-df2e8180-a08d-11e8-9703-9efea0c3d774.png)

**Comment by ManuelVargas1251** [comment]
@lucas-garcon I'm closing this issue and re-opening since we got a false start with a user that don't exist no more
